// 각 캐릭터의 무브리스트 데이터를 사전에 import 해놓은 객체
// 이 또한 React Native에서는 동적으로 경로를 import하는 것이 불가능하기 때문에 사전에 정의하여 사용
const importCharacterMoveData = {
    alisa: require("../assets/moveData/alisa_movelist.json"),
    asuka: require("../assets/moveData/asuka_movelist.json"),
    azucena: require("../assets/moveData/azucena_movelist.json"),
    "bryan-fury": require("../assets/moveData/bryan_fury_movelist.json"),
    "claudio-serafino": require("../assets/moveData/claudio_serafino_movelist.json"),
    "devil-jin": require("../assets/moveData/devil_jin_movelist.json"),
    "feng-wei": require("../assets/moveData/feng_wei_movelist.json"),
    hwoarang: require("../assets/moveData/hwoarang_movelist.json"),
    "jack-8": require("../assets/moveData/jack_8_movelist.json"),
    "jin-kazama": require("../assets/moveData/jin_kazama_movelist.json"),
    "jun-kazama": require("../assets/moveData/jun_kazama_movelist.json"),
    "kazuya-mishima": require("../assets/moveData/kazuya_mishima_movelist.json"),
    king: require("../assets/moveData/king_movelist.json"),
    kuma: require("../assets/moveData/kuma_movelist.json"),
    "lars-alexandersson": require("../assets/moveData/lars_alexandersson_movelist.json"),
    lee: require("../assets/moveData/lee_movelist.json"),
    leo: require("../assets/moveData/leo_movelist.json"),
    "leroy-smith": require("../assets/moveData/leroy_smith_movelist.json"),
    lili: require("../assets/moveData/lili_movelist.json"),
    "ling-xiaoyu": require("../assets/moveData/ling_xiaoyu_movelist.json"),
    "marshall-law": require("../assets/moveData/marshall_law_movelist.json"),
    "nina-williams": require("../assets/moveData/nina_williams_movelist.json"),
    panda: require("../assets/moveData/panda_movelist.json"),
    "paul-phoenix": require("../assets/moveData/paul_phoenix_movelist.json"),
    raven: require("../assets/moveData/raven_movelist.json"),
    reina: require("../assets/moveData/reina_movelist.json"),
    "sergei-dragunov": require("../assets/moveData/sergei_dragunov_movelist.json"),
    shaheen: require("../assets/moveData/shaheen_movelist.json"),
    "steve-fox": require("../assets/moveData/steve_fox_movelist.json"),
    "victor-chevalier": require("../assets/moveData/victor_chevalier_movelist.json"),
    yoshimitsu: require("../assets/moveData/yoshimitsu_movelist.json"),
    zafina: require("../assets/moveData/zafina_movelist.json"),
    "eddy-gordo": require("../assets/moveData/eddy_gordo_movelist.json"),
};

export default importCharacterMoveData;
